version: '2'
services:
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
  container_name: elasticsearch
  environment:
   - discovery.type=single-node
  ports:
   - "9200:9200"

 logstash:
  image: docker.elastic.co/logstash/logstash:7.17.9
  container_name: logstash
  ports:
   - "5044:5044"
  volumes:
   - ./logstash-gate.conf:/usr/share/logstash/pipeline/logstash.conf:ro
   - ./gate_logs.log:/data/gate_logs.log:ro

 kibana:
  image: docker.elastic.co/kibana/kibana:7.17.9
  container_name: kibana
  ports:
   - "5601:5601"
