conf id="logstashsnort"
input {
 file {
  path => "/var/log/snort/alert"
  start_position => "beginning"
 }
}

output {
 elasticsearch {
  hosts => ["http://localhost:9200"]
  index => "snort-alerts-%{+YYYY.MM.dd}"
 }
 stdout { codec => rubydebug }
}
