input {
  http_poller {
    urls => {
      malicious_ips => "http://localhost:8000/malicious-ips-feed.json"
    }
    request_timeout => 60
    interval => 3600
    codec => "json"
  }
}

filter {
  split { field => "[malicious_ips]" }
  mutate {
    rename => { "[malicious_ips]" => "ip" }
    add_field => { "feed" => "%{[feed_name]}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "threat-feed"
  }
  stdout { codec => rubydebug }
}
