input {
  file {
    path => "/var/log/fail2ban.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp}\s+%{WORD:program}\.%{WORD:component}\s+\[%{NUMBER:pid}\]:\s+%{WORD:level}\s+%{GREEDYDATA:details}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "fail2ban-%{+YYYY.MM.dd}"
  }
}
