input {
  stdin { }
}

filter {
  grok {
    match => {
      "message" => "%{SYSLOGTIMESTAMP:logdate} %{DATA:logsource} %{DATA:program}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:logmessage}"
    }
  }

  grok {
    match => { "logmessage" => "from %{IP:src_ip} port %{INT:src_port}" }
    tag_on_failure => ["_grok_ip_extract_failed"]
  }
}

output {
  stdout { codec => rubydebug }
}
