## NXLog Community Edition - Example config to forward Windows Event Logs to Syslog-ng
## Target Syslog-ng server: 172.31.10.232:514 (UDP)

<Input in>
    Module      im_msvistalog
</Input>

<Output out>
    Module      om_udp
    Host        172.31.10.232
    Port        514
    Exec        to_syslog_ietf();
</Output>

<Route 1>
    Path in => out
</Route>
